#!/usr/bin/env bash
npm run build
sudo cp -r ./dist/* /var/www/html
export PUBLIC_IP=$(curl -4 ifconfig.me) 
echo "Server hosted on following: http://$PUBLIC_IP/"
sudo rm -rf /var/www/73.160.140.242/*
sudo cp -R dist/* /var/www/73.160.140.242/
sudo systemctl reload nginx

