#!/usr/bin/bash
sudo unlink /etc/nginx/sites-enabled/*
sudo ln -s /etc/nginx/sites-available/adamattia.me /etc/nginx/sites-enabled/
sudo nginx -t
pm2 start index.js
sudo systemctl reload nginx
echo "Done!"